# Generated by Django 4.0 on 2024-09-20 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='contact',
        ),
    ]
