# Generated by Django 4.2.15 on 2024-09-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_id',
            new_name='produc_tid',
        ),
    ]
