# Generated by Django 4.2.15 on 2024-09-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_product_id_cartitem_produc_tid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='produc_tid',
            new_name='product_id',
        ),
    ]
