# Generated by Django 4.0 on 2024-09-19 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_produc_tid_cartitem_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
