# Generated by Django 4.0 on 2024-09-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_signup_groups_signup_is_active_signup_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='user_permissions',
        ),
    ]
