# Generated by Django 4.0 on 2024-09-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_cartitem_price_cartitem_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='address',
            field=models.CharField(default=type, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='contact',
            field=models.IntegerField(default=type),
            preserve_default=False,
        ),
    ]
