# Generated by Django 4.0 on 2024-09-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_signup_groups_remove_signup_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='buyer_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
