# Generated by Django 4.0 on 2024-09-19 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cartitem_address_cartitem_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='address',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='contact',
        ),
    ]
