# Generated by Django 4.0 on 2024-09-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_cartitem_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='contact',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
