# Generated by Django 4.0 on 2024-09-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_cartitem_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='contact',
        ),
    ]
