# Generated by Django 4.0 on 2024-09-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_cartitem_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='address',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='contact',
            field=models.IntegerField(default=type),
            preserve_default=False,
        ),
    ]
