# Generated by Django 4.0 on 2024-09-19 13:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_cartitem_address_remove_cartitem_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='address',
            field=models.CharField(default=api.models.get_default_address, max_length=255),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='contact',
            field=models.IntegerField(default=api.models.get_default_contact),
        ),
    ]
